DEPLOY:
  SCORE_WEIGHT: 0.60
  POS_WEIGHT: 0.30
  AREA_WEIGHT: 0.10
  MIN_BBOX_W: 0.05
  MIN_BBOX_H: 0.05
  MIN_BBOX_AREA: 0.01
  SCORE_THRESH_HIGH: 0.35
  DATA_SOURCE: 1 #0:query, 1:refence
  TOPN: 5
TEST:
  IMS_PER_BATCH: 1
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: ""
  IGNORE_CLASS_WEIGHT_BIAS: False
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 4000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.25
    USE_NMS_INTER_CLASS: True 
    NMS_INTER_CLASS: 0.5 
    USE_NMS_IOM: True 
    NMS_IOM: 0.8 
  ROI_BOX_HEAD:
    NUM_CLASSES: 12
    CLASS_WEIGHT: (1.0, )
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
INPUT:
  MIN_SIZE_TRAIN: (384, 416, 448, 480, 512)
  MIN_SIZE_TEST: 448
  MAX_SIZE_TEST: 1344
  FLIP_PROB_TRAIN: 0.5
  VERTICAL_FLIP_PROB_TRAIN: 0.1
  FLIP_90_PROB_TRAIN: 0.1
  CROP_PROB_TRAIN: 0.1
  BLUR_PROB_TRAIN: 0.5
  CONTRAST_PROB_TRAIN: 0.5
  HSV_PROB_TRAIN: 0.5
DATASETS:
  TRAIN: ("coco_test_det",)
  TEST: ("coco_test_det",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, 100000, 140000, 180000)
  MAX_ITER: 200000
  IMS_PER_BATCH: 2 #24
