MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/data/user/data/breezecheng/pytorch_project/maskrcnn-benchmark/pretrained_models/.torch/models/e2e_faster_rcnn_fbnet_600.pth"
  IGNORE_CLASS_WEIGHT_BIAS: True
  BACKBONE:
    CONV_BODY: FBNet
  FBNET:
    ARCH: "cham_v1a"
    BN_TYPE: "bn"
    WIDTH_DIVISOR: 8
    DW_CONV_SKIP_BN: True
    DW_CONV_SKIP_RELU: True
  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (16, )
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 200
    RPN_HEAD: FBNet.rpn_head
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 6
    FEATURE_EXTRACTOR: FBNet.roi_head
    NUM_CLASSES: 40
    CLASS_WEIGHT: (1.0, )
DATASETS:
  TRAIN: ("coco_human_parsing","coco_cat09","coco_shengxian","coco_jiadian2","coco_meizhuang_1w","coco_bag_purse_8000","coco_jiulei","coco_shouji_extra","coco_shoes","coco_cat06","coco_shipinbuchong","coco_zhubaoshoushi","coco_jiadian1_extra","coco_tushu","coco_cat04","coco_tushu1","coco_shouji","coco_muying_shipin","coco_jiazhuang","coco_car","coco_bag","coco_muying_jiaju","coco_meizhuang_2w","coco_wanjuyueqi","coco_cat05","coco_feicui","coco_cat10","coco_muying_wanjuyuqi","coco_suitcase_2w","coco_diannaobangong","coco_jiadian1","coco_ali_clothing","coco_hetianyu","coco_cat07","coco_jiadian2_extra","coco_shipinyinliao","coco_yiyaobaojian","coco_clothes_nohuman5k","coco_jiadian3","coco_shoujike_annotated","coco_neiyiku_4k","coco_chuju","coco_cat08","coco_cat11","coco_jiaju","coco_tushu2","coco_shuma","coco_tushu3",)
  TEST: ("coco_shoujike_annotated",)
SOLVER:
  BASE_LR: 0.01125
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (90000, 120000)
  MAX_ITER: 135000
  IMS_PER_BATCH: 8  # for 12img/gpu, 2GPUs
# TEST:
#   IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (384, 416, 448, 480, 512)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 448
  MAX_SIZE_TEST: 1000
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]
